# Header
menu:
  Home: /
  Year 2021: /2021
  Year 2020: /2020
  Year 2019: /2019
  About: /about

# Default post title
default_post_title: Untitled

# Default post cover index page
default_cover_index: "https://7u0moq.bn.files.1drv.com/y4mQaqN6QFROz1lMnVUfHjAOr_YoySJ6dyTgFk8Fulb-QI_keHruv4Z_3xSnQZ2aF3JQM_RBV98CEp_c7BLSiMlJ73IRInR61Gg0nEbPdPjjVaqbQAAmoauD2qeQnyF1N9tk1sN-apQtyAt8saxDAKK102wd6cJet94kgBGccs4i_E6S2PZ6-dwRs7Lffwu-btxB5syNNok4UBxCWBQOPndQA?width=1300&height=500&cropmode=none"

# Default post cover index page
default_cover_detail: "https://7u0moq.bn.files.1drv.com/y4mQaqN6QFROz1lMnVUfHjAOr_YoySJ6dyTgFk8Fulb-QI_keHruv4Z_3xSnQZ2aF3JQM_RBV98CEp_c7BLSiMlJ73IRInR61Gg0nEbPdPjjVaqbQAAmoauD2qeQnyF1N9tk1sN-apQtyAt8saxDAKK102wd6cJet94kgBGccs4i_E6S2PZ6-dwRs7Lffwu-btxB5syNNok4UBxCWBQOPndQA?width=1300&height=500&cropmode=none"

# Favicon
favicon: ""

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname:
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light
  # Valine comments https://valine.js.org
  valine:
    appid:  # your leancloud appid
    appkey:  # your leancloud appkey
    notify: false # true/false:mail notify !!!Test,Caution. https://github.com/xCss/Valine/wiki/Valine-%E8%AF%84%E8%AE%BA%E7%B3%BB%E7%BB%9F%E4%B8%AD%E7%9A%84%E9%82%AE%E4%BB%B6%E6%8F%90%E9%86%92%E8%AE%BE%E7%BD%AE
    verify: false # true/false:verify code
    avatar: mm # avatar style https://github.com/xCss/Valine/wiki/avatar-setting-for-valine
    placeholder: Just go go # comment box placeholder


# Google Analytics Tracking ID
google_analytics:

# Social Accounts
twitter_url:
facebook_url: 
behance_url: 
googleplus_url: 
dribble_url: 
rss_url:
instagram_url:
youtube_url:
